#!/usr/bin/env python

"""
Assign an Elastic IP to THIS instance, allocate new if required
-------------------------------------------------------------------
Creator: Dave North <dnorth98@gmail.com>
Requires: boto  - http://boto.cloudhackers.com/en/latest/index.html
"""

import syslog
import boto.ec2
import boto.utils

def myLog(message):
    procName = __file__
    syslogMsg = procName + ": " + message
    syslog.syslog(syslogMsg)
    print '%s' % message

# get our current region and instance ID for "this" instance
region = boto.utils.get_instance_metadata()['placement']['availability-zone'][:-1]
current_instance_id = boto.utils.get_instance_metadata()['instance-id']

conn = boto.ec2.connect_to_region(region)

# Get a list of all elastic IPs
all_region_eips = conn.get_all_addresses()

proceedWithAssignment = True
elasticIP = ""

for eip in all_region_eips:
    if ( eip.domain == "standard" ):
        if (eip.instance_id == current_instance_id):
            # There is already an EIP assigned to this instance
            myLog("This instance is already using elastic IP: %s" % eip.public_ip)
            elasticIP = eip.public_ip
            proceedWithAssignment = False

        if ( (not eip.instance_id) and (not elasticIP) ):
            # this is an unallocated address
            myLog("Found an unallocated candidate elastic IP to use: %s" % eip.public_ip)
            elasticIP = eip.public_ip

# See if we need to provision a new elastic IP
if ( (not elasticIP) and (proceedWithAssignment) ):
    myLog("No unallocated elastic IP addresses - provisioning new")
    try:
        newElasticIP = conn.allocate_address()
    except Exception as e:
        myLog("Failed to provision new elastic IP: %s" % e)

    if (newElasticIP):
        elasticIP = newElasticIP.public_ip
        myLog("Provisioned new elastic IP: %s" % elasticIP)
        
# Now associate the address with this instance
if (proceedWithAssignment):
    myLog("Assigning elastic IP: %s" % elasticIP)

    result = conn.associate_address(current_instance_id, elasticIP)
    if (result):
        myLog("Successfully associated elastic IP %s with instanceID %s" % (elasticIP,current_instance_id))
else:
    myLog("Not proceeding with elastic IP assignment - elastic IP already assigned")
