#!/bin/bash

# Obtain acces and secret keys from the AWS instance metadata
# Handy if an instance is running with a role and you have a utility that is not role aware

# NOTE that the jq package MUST be installed to use this
# jq is a handy json parsing utility (yum install jq)

# what IAM role is this instance running under?
IAMROLE=`wget -q -O - http://169.254.169.254/latest/meta-data/iam/security-credentials`

CREDENTIALSJSON=`wget -q -O - http://169.254.169.254/latest/meta-data/iam/security-credentials/${IAMROLE}`

ACCESSKEY=`echo $CREDENTIALSJSON | jq -r '. | .["AccessKeyId"]'`
SECRETKEY=`echo $CREDENTIALSJSON | jq -r '. | .["SecretAccessKey"]'`

echo access $ACCESSKEY
echo secret $SECRETKEY
